import type { Dorm } from "./types";

// Mock dorm listings around Khon Kaen University.
// travel[] minutes are indicative "to campus core" values for the prototype.
export const DORMS: Dorm[] = [
  {
    id: "dorm-a",
    name: "หอพัก The Nest กังสดาล",
    zone: "กังสดาล",
    verified: true,
    usesSmartBilling: true,
    roomType: ["single", "double"],
    hasAir: true,
    rent: 3800,
    estElectric: 600,
    estWater: 120,
    internet: 200,
    deposit: 8000,
    minContract: "1y",
    amenities: ["wifi", "washer", "parking", "keycard", "aircon"],
    security: ["keycard", "cctv", "guard", "lighting"],
    travel: { walk: 22, motorcycle: 8, songthaew: 14, other: 12 },
    vacant: 4,
    rating: 4.6,
    highlights: ["อยู่ในงบรวม", "ใกล้คณะ", "ระบบคีย์การ์ดล็อก 2 ชั้น", "ได้ตรา Verified"],
    cautions: ["ค่าแรกเข้าค่อนข้างสูง"],
    lat: 16.474,
    lng: 102.822,
    image: "🏠",
  },
  {
    id: "dorm-b",
    name: "หอพักบ้านสวนเรสซิเดนซ์",
    zone: "กังสดาล",
    verified: true,
    usesSmartBilling: true,
    roomType: ["single"],
    hasAir: false,
    rent: 3200,
    estElectric: 500,
    estWater: 100,
    internet: 300,
    deposit: 6500,
    minContract: "6m",
    amenities: ["wifi", "parking", "fan"],
    security: ["cctv", "lighting"],
    travel: { walk: 30, motorcycle: 12, songthaew: 14, other: 16 },
    vacant: 7,
    rating: 4.1,
    highlights: ["ราคาดี", "ค่าแรกเข้าต่ำ", "Wi-Fi ฟรี"],
    cautions: ["ระยะทางไกลกว่าตัวเลือกอื่น", "ไม่มีลิฟต์ (อยู่ชั้น 3)", "พัดลม ไม่มีแอร์"],
    lat: 16.469,
    lng: 102.818,
    image: "🌿",
  },
  {
    id: "dorm-c",
    name: "หอพัก Gate View มอดินแดง",
    zone: "ประตู มข.",
    verified: true,
    usesSmartBilling: true,
    roomType: ["single", "double"],
    hasAir: true,
    rent: 4200,
    estElectric: 620,
    estWater: 130,
    internet: 150,
    deposit: 7000,
    minContract: "1y",
    amenities: ["wifi", "washer", "parking", "lift", "keycard", "aircon"],
    security: ["keycard", "cctv", "guard", "lighting"],
    travel: { walk: 15, motorcycle: 6, songthaew: 10, other: 9 },
    vacant: 2,
    rating: 4.8,
    highlights: ["ติดประตู มข.", "ความปลอดภัยสูงมาก", "เจ้าของดูแลดี", "มีลิฟต์"],
    cautions: ["Total Cost สูงกว่างบที่ตั้งไว้เล็กน้อย"],
    lat: 16.478,
    lng: 102.826,
    image: "🚪",
  },
  {
    id: "dorm-d",
    name: "หอพักศรีจันทร์เพลส",
    zone: "ศรีจันทร์",
    verified: false,
    usesSmartBilling: false,
    roomType: ["single"],
    hasAir: true,
    rent: 3500,
    estElectric: 750, // ค่าไฟแฝงสูง
    estWater: 200,
    internet: 250,
    deposit: 7000,
    minContract: "1y",
    amenities: ["wifi", "aircon", "parking"],
    security: ["cctv"],
    travel: { walk: 40, motorcycle: 15, songthaew: 20, other: 18 },
    vacant: 5,
    rating: 3.4,
    highlights: ["ห้องกว้าง", "มีแอร์"],
    cautions: ["ยังไม่ได้ตรา Verified", "คิดค่าไฟหน่วยละสูง (ไม่โปร่งใส)", "ไกลจากมหาวิทยาลัย"],
    lat: 16.44,
    lng: 102.83,
    image: "🏢",
  },
  {
    id: "dorm-e",
    name: "หอพัก U-Center บึงสีฐาน",
    zone: "บึงสีฐาน",
    verified: true,
    usesSmartBilling: true,
    roomType: ["single", "double"],
    hasAir: true,
    rent: 4500,
    estElectric: 650,
    estWater: 120,
    internet: 0, // รวมในค่าส่วนกลาง
    deposit: 9000,
    minContract: "1y",
    amenities: ["wifi", "washer", "parking", "lift", "keycard", "aircon", "gym"],
    security: ["keycard", "cctv", "guard", "lighting"],
    travel: { walk: 18, motorcycle: 7, songthaew: 12, other: 10 },
    vacant: 3,
    rating: 4.7,
    highlights: ["สิ่งอำนวยความสะดวกครบ", "มีฟิตเนส", "เน็ตรวมในค่าส่วนกลาง"],
    cautions: ["ค่าเช่าสูง", "ค่าแรกเข้าสูง"],
    lat: 16.462,
    lng: 102.83,
    image: "🏬",
  },
  {
    id: "dorm-f",
    name: "หอพักดอกคูนอพาร์ตเมนต์",
    zone: "กังสดาล",
    verified: false,
    usesSmartBilling: false,
    roomType: ["single"],
    hasAir: false,
    rent: 2500,
    estElectric: 450,
    estWater: 90,
    internet: 200,
    deposit: 5000,
    minContract: "monthly",
    amenities: ["wifi", "fan", "parking"],
    security: ["lighting"],
    travel: { walk: 25, motorcycle: 10, songthaew: 13, other: 14 },
    vacant: 8,
    rating: 3.2,
    highlights: ["ราคาถูกสุด", "สัญญารายเดือนได้", "ค่าแรกเข้าต่ำ"],
    cautions: ["ยังไม่ได้ตรา Verified", "ความปลอดภัยน้อย (ไม่มีกล้อง/ยาม)", "ไม่มีแอร์"],
    lat: 16.471,
    lng: 102.815,
    image: "🌼",
  },
  {
    id: "dorm-g",
    name: "หอพัก Smart Living เหล่านาดี",
    zone: "เหล่านาดี",
    verified: true,
    usesSmartBilling: true,
    roomType: ["single", "double"],
    hasAir: true,
    rent: 3900,
    estElectric: 580,
    estWater: 110,
    internet: 200,
    deposit: 7500,
    minContract: "6m",
    amenities: ["wifi", "washer", "parking", "keycard", "aircon", "lift"],
    security: ["keycard", "cctv", "lighting"],
    travel: { walk: 28, motorcycle: 11, songthaew: 15, other: 13 },
    vacant: 6,
    rating: 4.3,
    highlights: ["สัญญา 6 เดือนได้", "มีลิฟต์", "บิลโปร่งใส"],
    cautions: ["เดินทางไกลกว่าตัวเลือกโซนกังสดาล"],
    lat: 16.455,
    lng: 102.81,
    image: "⚡",
  },
  {
    id: "dorm-h",
    name: "หอพักมิตรภาพ มข.",
    zone: "ประตู มข.",
    verified: true,
    usesSmartBilling: true,
    roomType: ["double"],
    hasAir: true,
    rent: 2800, // ห้องคู่ หารกันถูก
    estElectric: 520,
    estWater: 110,
    internet: 180,
    deposit: 5500,
    minContract: "1y",
    amenities: ["wifi", "parking", "keycard", "aircon"],
    security: ["keycard", "cctv", "guard"],
    travel: { walk: 16, motorcycle: 7, songthaew: 11, other: 10 },
    vacant: 4,
    rating: 4.2,
    highlights: ["เหมาะแชร์ห้องคู่", "ใกล้ประตู มข.", "ค่าแรกเข้าไม่สูง"],
    cautions: ["มีเฉพาะห้องคู่ (ต้องหารูมเมท)"],
    lat: 16.477,
    lng: 102.824,
    image: "🤝",
  },
];
